 SET GLOBAL FOREIGN_KEY_CHECKS = 0;
 commit; 
DROP TABLE `ACHATS`, `APPORTS`, `CAGNOTTES`, `COLOCATIONS`, `HISTORIQUES`, `IMPLICATION`, `LOGINS`, `PERSONNES`, `VERSEMENTS`;
commit;
 SET GLOBAL FOREIGN_KEY_CHECKS = 1; 
 